#!/bin/bash
# combustion: prepare network
set -euxo pipefail
exec &>/dev/ttyS0
# Poweroff immediately on any failure to avoid unnecessary waiting.
trap '[ $? -eq 0 ] || poweroff -f' EXIT

if [ "${1-}" = "--prepare" ]; then
	# Verify that the udev rules work for all config sources and avoid
	# the timeout on boot.
	if ! systemctl is-active dev-combustion-config.device; then
		echo "FAILED: timeout"
		exit 1
	fi

	exit 0
fi

echo root:linux | chpasswd
curl example.com
echo "Configured with combustion" > /etc/issue.d/combustion

# Make sure that the system comes up good, leave a marker in the shared FS
# and power off the VM.
cat >>/usr/bin/combustion-validate <<'EOF'
#!/bin/bash
set -euxo pipefail
exec &>/dev/ttyS0
trap '[ $? -eq 0 ] || poweroff -f' EXIT
if journalctl --no-pager | grep "/sysroot still mounted somewhere"; then
    exit 1
fi
mount -t virtiofs tmpdir /mnt
touch /mnt/done
umount /mnt
poweroff -f
EOF
chmod a+x /usr/bin/combustion-validate

cat >>/etc/systemd/system/combustion-validate.service <<'EOF'
[Service]
ExecStart=/usr/bin/combustion-validate
[Install]
RequiredBy=default.target
EOF
systemctl enable combustion-validate.service
